# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_slug'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='question',
        ),
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(to='questions.Question'),
        ),
    ]
