# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170816_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservotes',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
