# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answervote',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionvote',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answervote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_vote', to='answers.Answer'),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_vote', to='questions.Question'),
        ),
    ]
